### ISSUE TITLE
PocketItem Equals method is broken

### ISSUE THREAD

**Issue by fujiy** [ceee/PocketSharp#32] opened 2016-02-21 02:24 UTC
It is broken here: https://github.com/ceee/PocketSharp/blob/master/PocketSharp/Models/PocketItem.cs#L414

**Comment by ceee** [comment] 2016-02-21 12:29
Hi. Thanks for your PR.
I will add a failing unit test which checks the equality operator + equals and merge your changes afterwards.

**Comment by ceee** [comment] 2016-02-21 12:46
I can't reproduce the fail. I have added the equality tests and they pass with the current implementation. See here: https://github.com/ceee/PocketSharp/commit/49436e0aaaff5dd045ca71fe37d944a5c7266329

Could you please provide more information on how and where it is broken and how to reproduce it?

**Comment by fujiy** [comment] 2016-02-21 18:39
You need to pass a diferent type of object to Equals as argument, so the cast will fail

**Comment by ceee** [comment] 2016-02-21 22:29
Thanks, confirmed.

**Comment by ceee** [comment] 2016-02-21 22:33
Merged #34 and will update the NuGet package soon. Thanks for your contribution :)

**Closed by ceee** 2016-02-21 22:33 UTC
